---
- name: "Install dependencies"
  hosts: management
  user: ubuntu
  gather_facts: false
  become: yes
  pre_tasks:
    - name: "Install 'unzip'"
      apt:
        name: [ "unzip" ]
        state: latest
        update_cache: yes

  roles:
    - install-awscli
    - install-kubectl

- name: "Authenticate AWS CLI with AWS"
  hosts: management
  user: ubuntu
  gather_facts: false
  become: yes

    # Get the environment variables from CircleCI and add to the EC2 instance
  environment:
    - AWS_ACCESS_KEY_ID: "{{ lookup('env', 'AWS_ACCESS_KEY_ID')}}"  
    - AWS_SECRET_ACCESS_KEY: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY')}}"  
    - AWS_SESSION_TOKEN: '{{ lookup(''env'', ''AWS_SESSION_TOKEN'')}}'
    - AWS_DEFAULT_REGION: '{{ lookup(''env'', ''AWS_DEFAULT_REGION'')}}'

  # vars:
  #   AWS_ACCESS_KEY_ID: "{{ lookup('env','AWS_ACCESS_KEY_ID') }}"
  #   AWS_SECRET_ACCESS_KEY: "{{ lookup('env','AWS_SECRET_ACCESS_KEY') }}"
  #   AWS_SESSION_TOKEN: "{{ lookup('env','AWS_SESSION_TOKEN') }}"
  #   AWS_DEFAULT_REGION: "{{ lookup('env', 'AWS_DEFAULT_REGION') }}"
  tasks:
    - name: Show environment variable
      shell: |
        echo "AWS_ACCESS_KEY_ID $AWS_ACCESS_KEY_ID "
        echo "AWS_SECRET_ACCESS_KEY $AWS_SECRET_ACCESS_KEY "
        echo "AWS_SESSION_TOKEN $AWS_SESSION_TOKEN "
        echo "AWS_DEFAULT_REGION $AWS_DEFAULT_REGION "

    - name: Set the aws_access_key_id
      shell: "aws --profile default configure set aws_access_key_id $AWS_ACCESS_KEY_ID "
    - name: Set the aws_secret_access_key
      shell: "aws --profile default set aws_secret_access_key $AWS_SECRET_ACCESS_KEY "
    - name: Set the aws_session_token
      shell: "aws --profile default configure set aws_secret_access_key $AWS_SESSION_TOKEN "
    - name: Set the default.region
      shell: "aws --profile default configure set region $AWS_DEFAULT_REGION"

- name: "Fetch kubectl config"
  hosts: management
  user: ubuntu
  gather_facts: false
  become: yes

  environment:
    - AWS_ACCESS_KEY_ID: "{{ lookup('env', 'AWS_ACCESS_KEY_ID')}}"  
    - AWS_SECRET_ACCESS_KEY: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY')}}"  
    - AWS_SESSION_TOKEN: '{{ lookup(''env'', ''AWS_SESSION_TOKEN'')}}'
    - AWS_DEFAULT_REGION: '{{ lookup(''env'', ''AWS_DEFAULT_REGION'')}}'

  # vars:
  #   AWS_DEFAULT_REGION: "{{ lookup('env', 'AWS_DEFAULT_REGION') }}"
  #   ENVIRONMENT_NAME: "{{ lookup('env', 'ENVIRONMENT_NAME') }}"
  pre_tasks:
    - name: Create a kubeconfig file for the cluster
      shell: "aws eks update-kubeconfig --region $AWS_DEFAULT_REGION --name ${ENVIRONMENT_NAME}-cluster"
