---

- name: "Fetch kubectl config"
  hosts: management
  user: ubuntu
  gather_facts: false
  become: yes

  pre_tasks:
    - name: Grant docker an start minikube
      shell: |
        sudo usermod -aG docker $USER && newgrp docker
        minikube start
