- name: "Install the minikube"
  shell: |
    curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
    sudo install minikube-linux-amd64
  args:
    chdir: $HOME

- name: "Check install the minikube"
  shell: |
    which minikube
    minikube version

- name: "Start the minikube"
  shell: |
    minikube start
