---
- name: "Download kubectl"
  shell: |
    curl -O https://s3.us-west-2.amazonaws.com/amazon-eks/1.26.2/2023-03-17/bin/linux/amd64/kubectl
  args:
    chdir: $HOME

- name: "erify the downloaded binary with the SHA-256 checksum for binary"
  shell: |
    curl -O https://s3.us-west-2.amazonaws.com/amazon-eks/1.26.2/2023-03-17/bin/linux/amd64/kubectl.sha256
  args:
    chdir: $HOME

- name: "Check the SHA-256 checksum for downloaded binary"
  shell: |
    sha256sum -c kubectl.sha256
  args:
    chdir: $HOME

- name: "Download kubectl"
  shell: |
    openssl sha1 -sha256 kubectl
  args:
    chdir: $HOME

- name: "Apply execute permissions to the binary"
  shell: chmod +x ./kubectl
  args:
    chdir: $HOME

- name: "Copy the binary to a folder to the $PATH"
  shell: mkdir -p $HOME/bin && cp ./kubectl $HOME/bin/kubectl && export PATH=$HOME/bin:$PATH
  args:
    chdir: $HOME

- name: "Add the $HOME/bin path to the shell initialization file"
  shell: echo 'export PATH=$HOME/bin:$PATH' >> ~/.bashrc
  args:
    chdir: $HOME

- name: "Check install the kubectl"
  shell: |
    which kubectl
    kubectl version --short --client