- name: "Install dependencies docker"
  shell: |
    # sudo rm /var/lib/apt/lists/lock
    # sudo rm /var/cache/apt/archives/lock
    # sudo rm /var/lib/dpkg/lock*
    # sudo dpkg --configure -a
    sudo apt-get update -y
    sudo apt install apt-transport-https ca-certificates software-properties-common -y
  args:
    chdir: $HOME

- name: "Docker certificates"
  shell: |
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  args:
    chdir: $HOME

- name: "Download docker"
  shell: |
    sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  args:
    chdir: $HOME

- name: "Install docker"
  shell: |
    sudo apt update -y
    apt-cache policy docker-ce
    sudo apt install docker-ce -y
  args:
    chdir: $HOME

- name: "Check install the Docker"
  shell: |
    sudo systemctl status docker

- name: "Grant permission the Docker"
  shell: |
    # sudo usermod -aG docker $USER && newgrp docker
    sudo chmod 660 /var/run/docker.sock

- name: "Download and Install kubectl"
  shell: |
    curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
    sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
  args:
    chdir: $HOME

- name: "Add the $HOME/bin path to the shell initialization file"
  shell: echo 'export PATH=$HOME/bin:$PATH' >> ~/.bashrc
  args:
    chdir: $HOME

- name: "Check install the kubectl"
  shell: |
    which kubectl
    kubectl version --short --client

- name: "Install the minikube"
  shell: |
    curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
    sudo install minikube-linux-amd64 /usr/local/bin/minikube
  args:
    chdir: $HOME

- name: "Check install the minikube"
  shell: |
    which minikube
    minikube version

- name: "Start the minikube"
  shell: |
    minikube start

- name: "Check status the minikube"
  shell: |
    minikube status