version: 2.1

jobs:
  # test-build:
  #   docker:
  #     - image: python:3.7.3-stretch
  #   steps:
  #     - checkout
  #     - restore_cache:
  #         keys:
  #         - v1-dependencies-{{ checksum "requirements.txt" }}
  #         - v1-dependencies-
  #     - run:
  #         name: install dependencies
  #         command: |
  #           python3 -m venv venv
  #           . venv/bin/activate
  #           make install
  #     - save_cache:
  #         paths:
  #           - ./venv
  #         key: v1-dependencies-{{ checksum "requirements.txt" }}
  #     # run tests!
  #     - run:
  #         name: run tests
  #         command: |
  #           . venv/bin/activate
  #           make test
  #     # run lints!
  #     - run:
  #         name: run lint
  #         command: |
  #           . venv/bin/activate
  #           make lint

  # upload-docker:
  #   description: Upload to Dockerhub
  #   docker:
  #     - image: docker:stable
  #   working_directory: ~/repo
  #   steps:
  #     - checkout
  #     - setup_remote_docker:
  #         version: 20.10.14
  #     - run:
  #         name: Build docker container
  #         command: |
  #           docker build --tag=$DOCKER_IMAGE_NAME .
  #           docker image ls
  #     - run:
  #         name: Upload Docker to Dockerhub
  #         command: |
  #           echo "Docker ID and Image: $DOCKER_IMAGE_NAME"
  #           docker login -u="$DOCKERHUB_USERNAME" -p="$DOCKERHUB_PASSWORD"
  #           docker tag $DOCKER_IMAGE_NAME $DOCKERHUB_USERNAME/$DOCKER_IMAGE_NAME:${CIRCLE_WORKFLOW_ID:0:7}
  #           docker push $DOCKERHUB_USERNAME/$DOCKER_IMAGE_NAME:${CIRCLE_WORKFLOW_ID:0:7}
  
  deploy-infrastructure:
    description: Deploy Infrastructure EKS
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yum install -y tar gzip
      
      # - run:
      #     name: Ensure EKS network exists
      #     command: |
      #       aws cloudformation deploy \
      #         --template-file cloudformation/networks.yml \
      #         --tags project=${ENVIRONMENT_NAME}-project \
      #         --stack-name ${ENVIRONMENT_NAME}-eks-network \
      #         --region us-east-1
      # - run:
      #     name: Ensure EKS Cluster exists
      #     command: |
      #       aws cloudformation deploy \
      #         --template-file cloudformation/cluster.yml \
      #         --tags project=${ENVIRONMENT_NAME}-project \
      #         --stack-name "${ENVIRONMENT_NAME}-eks-cluster" \
      #         --capabilities CAPABILITY_NAMED_IAM \
      #         --region us-east-1
      #     no_output_timeout: 15m
      # - run:
      #     name: Ensure Nodegroup exists
      #     command: |
      #       aws cloudformation deploy \
      #         --template-file cloudformation/nodegroup.yml \
      #         --tags project=${ENVIRONMENT_NAME}-project \
      #         --stack-name "${ENVIRONMENT_NAME}-eks-nodegroup" \
      #         --capabilities CAPABILITY_NAMED_IAM \
      #         --region us-east-1
      - run:
          name: Show info instances
          command: |
            aws ec2 create-default-subnet
            aws ec2 describe-instances
      - run:
          name: Ensure management instances exists
          command: |
            aws cloudformation deploy \
              --template-file cloudformation/management.yml \
              --tags project=${ENVIRONMENT_NAME}-project \
              --stack-name "${ENVIRONMENT_NAME}-eks-management" \
              --region us-east-1 \
              --output text >> ~/checkDeployed.txt
            cat ~/checkDeployed.txt
      - run:
          name: Extract the IPs of the management instances for Ansible
          command: |
            echo [management] > ~/inventory.txt
            aws ec2 describe-instances \
              --query 'Reservations[*].Instances[*].PublicIpAddress' \
              --filters "Name=tag:Name,Values=${ENVIRONMENT_NAME}-management*" \
              --region us-east-1 \
              --output text >> ~/inventory.txt
            cat ~/inventory.txt
      - persist_to_workspace:
          root: ~/
          paths:
            - inventory.txt
            - checkIfDeployed.txt

      # - run:
      #     name: Destroy environments
      #     when: on_fail
      #     command: |
      #       echo "Destroying environment: deploy-infrastructure "
      #       aws cloudformation delete-stack --stack-name ${ENVIRONMENT_NAME}-eks-network
      #       aws cloudformation delete-stack --stack-name ${ENVIRONMENT_NAME}-eks-cluster
      #       aws cloudformation delete-stack --stack-name ${ENVIRONMENT_NAME}-eks-management

workflows:
  default:
    jobs:
      # - test-build
      # - upload-docker:
      #     requires:
      #       - test-build
      - deploy-infrastructure