- name: "Install dependencies docker"
  shell: |
    sudo apt install apt-transport-https ca-certificates software-properties-common
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  args:
    chdir: $HOME

- name: "Download docker"
  shell: |
    sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  args:
    chdir: $HOME

- name: "Install docker"
  shell: |
    sudo apt update -y
    apt-cache policy docker-ce
    sudo apt install docker-ce -y
  args:
    chdir: $HOME

- name: "Check install the Docker"
  shell: |
    sudo systemctl status docker
