---
- name: "Download kubectl"
  shell: curl -o kubectl https://amazon-eks.s3.us-west-2.amazonaws.com/1.19.6/2021-01-05/bin/linux/amd64/kubectl
  args:
    chdir: $HOME

- name: "Apply execute permissions to the binary"
  shell: chmod +x ./kubectl
  args:
    chdir: $HOME

- name: "Copy the binary to a folder to the $PATH"
  shell: mkdir -p $HOME/bin && cp ./kubectl $HOME/bin/kubectl && export PATH=$PATH:$HOME/bin
  args:
    chdir: $HOME

- name: "Add the $HOME/bin path to the shell initialization file"
  shell: echo 'export PATH=$PATH:$HOME/bin' >> .bashrc
  args:
    chdir: $HOME

# - name: "Download and Install kubectl"
#   shell: |
#     curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
#     sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
#   args:
#     chdir: $HOME

# - name: "Add the $HOME/bin path to the shell initialization file"
#   shell: echo 'export PATH=$HOME/bin:$PATH' >> ~/.bashrc
#   args:
#     chdir: $HOME

# - name: "Check install the kubectl"
#   shell: |
#     which kubectl
#     kubectl version --short --client
    