apiVersion: v1
kind: Service
metadata:
  name: devops-capstone-service
spec:
  type: LoadBalancer
  selector:
    app: devops-capstone
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
