apiVersion: v1
kind: Service
metadata:
  name: Luannt19-Uda-service
spec:
  type: LoadBalancer
  selector:
    app: Luannt19-Uda-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
